"""Create a program that will play the cows and bulls game with the user. The game works like this
Randomly generate a 4 digit number. Ask the user to guess a 4 digit number. For every digit that the user guessed correctly 
in the correct place, they have a cow. For every digit the user guessed correctly in the wrong place is a bull.
Every time the user makes a guess, tell them how many cows and bulls they have. 
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the
 game and tell the user at the end.Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
Until the user guesses the number."""

from random import randint
rand_num=str((randint(1000,9999)))
print "Welcome to the Cows and Bulls Game! \nRandom Number is :", rand_num
ui_num=raw_input("Please enter the guess:") 
def cowsbulls(rand_num,ui_num):
    cows=0
    bulls=0
    for i in range(len(str(rand_num))):
        if rand_num[i] == ui_num[range(len((ui_num)))[i]]:
            cows +=1
        else:
            bulls +=1
    #return cows,bulls
    print "Cows:%d Bulls:%d" % (cows,bulls)
    return (cows,bulls)
counter=0 
t_cows=0
t_bulls=0           

while (True):

    l=cowsbulls(rand_num,ui_num)
    counter +=1
    t_cows +=l[0]
    t_bulls +=l[1]
    if (l[0] == 4):
        print "\nGame over!!. \nTotal Guesses made are:%d \nTotal cows are:%d \nTotal bulls are: %d "  %(counter,t_cows,t_bulls)
        break
    else:
        ui_num=raw_input("Guess Another number:")
        continue

    

